/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Edit: typeof import('./components/Edit.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Note: typeof import('./components/Note.vue')['default']
    Options: typeof import('./components/Options.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
